name: CI/CD Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send POST request for static code analysis
      env:
        OWNER: "Thoparam-sai-nithish"
        REPO: "mega2k23"
        TOKEN: ${{secrets.pat_token}}
      run: |
        curl -X POST "https://codeanalysis.azurewebsites.net/CodeAnalysis/PerfromStaticCodeAnalysis?owner=${OWNER}&repo=${REPO}&token=${TOKEN}"
