name: Code Analysis

on:
  push:
    branches:
      - '**' # Triggers on push to any branch

jobs:
  analyze_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send POST request to code analysis API
      id: send_request
      run: |
        owner=${{ github.repository_owner }}
        repo=${{ github.repository }}
        token=${{ secrets.MY_CUSTOM_TOKEN }}
        response=$(curl -s -X POST "https://codeanalysis.azurewebsites.net/CodeAnalysis/PerfromStaticCodeAnalysis?owner=$owner&repo=$repo&token=$token")
        echo "Response: $response"
        echo "::set-output name=response::$response"

    - name: Print API response
      run: |
        echo "API Response: ${{ steps.send_request.outputs.response }}"

    - name: Check API response
      run: |
        if [ "${{ steps.send_request.outputs.response }}" != "true" ]; then
          echo "API Response is false. Failing the job."
          exit 1
        else
          echo "API Response is true. Job succeeded."
        fi
