name: Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send POST request to code analysis API
      run: |
        response=$(curl -s -X POST "https://codeanalysis.azurewebsites.net/CodeAnalysis/PerfromStaticCodeAnalysis?owner=Thoparam-sai-nithish&repo=mega2k23&token=${{ secrets.PAT_TOKEN }}")
        echo "Response: $response"

    - name: Print API response
      run: |
        echo "API Response: $response"
